apiVersion: v1
kind: ConfigMap
metadata:
  name: my-finance-config
  namespace: my-finance
data:
  NODE_ENV: production

  # Service Ports
  AUTH_SERVICE_PORT: "3002"
  TRANSACTION_SERVICE_PORT: "3001"
  REPORT_SERVICE_PORT: "3003"
  GROUP_SERVICE_PORT: "3004"
  ML_SERVICE_PORT: "3005"
  API_GATEWAY_PORT: "3000"

  # Service URLs (internal K8s DNS)
  AUTH_SERVICE_URL: http://auth-service:3002
  TRANSACTION_SERVICE_URL: http://transaction-service:3001
  REPORT_SERVICE_URL: http://report-service:3003
  GROUP_SERVICE_URL: http://group-service:3004
  ML_SERVICE_URL: http://ml-service:3005
  ML_API_URL: http://ml-python:5000

  # Redis
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_URL: redis://redis:6379

  # JWT
  JWT_ISSUER: my-finance-app
  JWT_EXPIRES_IN: 7d

  # ML
  USE_ML_MODEL: "true"
  USE_ENHANCED_KEYWORD: "true"
